---
{{- if and .Values.azure.keyvault_uri .Values.azure.tenant_id }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.azure.keyvault_uri | quote }}
      tenantId: {{ .Values.azure.tenant_id | quote }}
      serviceAccountRef:
        name: {{ .Values.clusterSecretStore.serviceAccountName }}
        namespace: {{ .Values.clusterSecretStore.serviceAccountNamespace }}
{{- end }}
