---
{{- if and .Values.demo.enabled .Values.azure.keyvault_uri }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.demo.externalSecretName }}
  namespace: {{ .Values.demo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "24"
spec:
  refreshInterval: {{ .Values.demo.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.demo.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: value
      remoteRef:
        key: {{ .Values.demo.remoteKey }}
{{- end }}
