---
{{- if (.Values.external_secrets.enabled) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.external_secrets.addon_name }}
  namespace: {{ .Values.global.control_plane.namespace }}
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd.argoproj.io/sync-wave: "22"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.control_plane.project }}
  source:
    repoURL: {{ .Values.global.control_plane.repo }}
    targetRevision: HEAD
    path: {{ printf "addon_charts/%s" .Values.external_secrets.addon_name }}
    helm:
      valueFiles:
        - values.yaml
      valuesObject:
        azure:
          tenant_id: {{ .Values.external_secrets.azure.tenant_id | quote }}
          workload_identity_client_id: {{ .Values.external_secrets.azure.workload_identity_client_id | quote }}
          keyvault_uri: {{ .Values.external_secrets.azure.keyvault_uri | quote }}
        external-secrets:
          serviceAccount:
            annotations:
              azure.workload.identity/client-id: {{ .Values.external_secrets.azure.workload_identity_client_id | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.external_secrets.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
      - Prune=true
      - ApplyOutOfSyncOnly=true
      - Force=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    {{- with .Values.global.control_plane.deployment }}
    retry:
      limit: {{ .limit }}
      backoff:
        duration: {{ .backoff.duration }}
        factor: {{ .backoff.factor }}
        maxDuration: {{ .backoff.maxDuration }}
    {{- end }}
{{- end }}
